[Android] Use `asReversed` instead of `reversed` (#3598)
## Description

Some of our users experience crashes that `reversed` is not defined:

```
java.lang.NoSuchMethodError: No virtual method reversed()Ljava/util/List;
```

This PR changes `reversed` occurrences to either `asReversed` (if possible), or `asReversed().toList()`, if array can be modified.

Closes #3594 

## Test plan

Tested on expo-example (mostly _transformations_, _multitap_).