Fix failing `Jest` CI (#3988)
## Description

Currently our CI fail with the following error:

```
ReferenceError: regeneratorRuntime is not defined
```

Based on [this issue
comment](https://github.com/jestjs/jest/issues/3126#issuecomment-723998132)
I've updated out `babel.config.js`. This fixed issue locally, so it
should also work on CI.

## Test plan

Check CI